Handle `abi.encode()` with empty args (#1801)
This is a small bugfix for the case when `abi.encode()` is called with
empty arguments.

Without this change, if you run the following command, you get a panic:
```sh
$ cargo run compile --target=polkadot testdata/solidity/test/libsolidity/semanticTests/abiEncoderV2/abi_encode_v2.sol
...
thread 'main' panicked at src/codegen/encoding/mod.rs:169:46:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The cause of the panic is this function:
```sol
    function f0() public pure returns (bytes memory) {
        return abi.encode();
    }
```
With the change, the command completes successfully.

Signed-off-by: Samuel Moelius <samuel.moelius@trailofbits.com>