public contract variable resolves to function type
This contract:

	contract bar {
		int public total;
	}

	contract foo is bar {
		function f1() public {
			int variable = total;
		}
	}

Produces the error:

error: conversion from int256 to function() internal returns (int256) not possible

In fact, we should resolve to a function type when the context requires
this.

Signed-off-by: Sean Young <sean@mess.org>