Error of garbage argument to builtin function not surfaced
A function call like:

	require("a" > 2);

Will just give the diagnostic:

	 error: cannot find overloaded function which matches signature

Signed-off-by: Sean Young <sean@mess.org>